### ISSUE TITLE
Not available in Maven Central

### ISSUE THREAD

**Issue by javagl** [openize-com/openize-drako-java#1]
Apparently, the library is not available on Maven Central. Neither under the coordinates 
```
<dependency>
  <groupId>org.openize</groupId>
  <artifactId>drako</artifactId>
  <version>1.4.0</version>
</dependency>
```
that are mentioned in https://products.fileformat.dev/drako/java/ , nor under the coordinates
```
<dependency>
  <groupId>org.fileformat</groupId>
  <artifactId>drako</artifactId>
  <version>1.0</version>
</dependency>
```
that are shown here in the README.

Also, in order to be used by others, the role of the [`com/aspose/csporter/helpers`](https://github.com/fileformat-drako/FileFormat.Drako-for-Java/tree/main/libs/com/aspose/csporter/helpers) has to be clarified. Both in terms of licensing, as well as in availability of the source code.

**Comment by lexchou-aspose** [comment]
I have deployed to [maven central repository](https://central.sonatype.com/namespace/dev.fileformat) today, and also fixed the dependency issue.
